### ISSUE TITLE
Documenter does not deploy

### ISSUE THREAD

**Issue by JeffFessler** [JeffFessler/AVSfldIO.jl#2]
Hi @johnnychen94, I invited you to this repo in hopes that you might be able to figure out why Documenter is not deploying for it.  I'm stuck, but if you don't have time I understand.  It is not urgent.  I think I have similar issues with other repos so I hope by seeing how it is fixed here I can do it correctly in the future.  Thanks!

**Comment by JeffFessler** [comment]
@johnnychen94 thanks to your help we now have docs for the "dev" version but the "stable" version still does not seem to deploy.  The badge that links to https://jefffessler.github.io/AVSfldIO.jl/stable gives a 404 error.
I suspect we might need the DOCUMENTER_KEY after all: 
https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions
I'm going to try it and see...

**Comment by johnnychen94** [comment]
`stable` version requires a new release/tag

> From: https://juliadocs.github.io/Documenter.jl/dev/lib/public/#Documenter.deploydocs
>
> Releases vs development branches
>
> deploydocs will automatically figure out whether it is deploying the documentation for a tagged release or just a development branch (usually, based on the environment variables set by the CI system).
>
> With versioned tags, deploydocs discards the build metadata (i.e. + and everything that follows it) from the version number when determining the name of the directory into which the documentation gets deployed. Pre-release identifiers are preserved.

**Comment by johnnychen94** [comment]
> I suspect we might need the DOCUMENTER_KEY after all:
https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions

This is because a GitHub action (TagBot CI) cannot trigger another GitHub action (docs CI/UnitTest) unless it's configured with an ssh key. Similarly, if you want CompatHelper to trigger UnitTests, you'll also need to add an ssh key for it.

The name of the ssh key doesn't matter, so it can be `TAGBOT`, or whatever you want. The docs use `DOCUMENTER_KEY` simply because people _must_ set up an ssh key to deploying documents back to the Travis CI days, and by reusing `DOCUMENTER_KEY`, people don't need to manage another ssh key.

For clarification, It's not adding `DOCUMENTER_KEY` to the docs CI, instead, it's adding it to TagBot/Compathelper CI.

See https://github.com/Evizero/Augmentor.jl/issues/72 for an example.

**Comment by JeffFessler** [comment]
Oh!  Finally I am starting to understand.  I love writing Julia code, but yml files are too mysterious for me.  Thank you!

I forced a new tag to try to trigger the docs for stable version:
```
git tag v0.2.0-doc
git push origin v0.2.0-doc
```
It still did not generate docs for stable version so I guess I wait for a new release.

**Comment by johnnychen94** [comment]
Docs for the tag v0.2.0-doc does get generated: https://jefffessler.github.io/AVSfldIO.jl/v0.2.0-doc/

Just wait until the next release sounds fine to me.
